# Generated by Django 5.2.1 on 2025-05-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(choices=[('🐍 Python for Beginners', 'Python'), ('⚡ JavaScript Essentials', 'Js'), ('🎨 HTML & CSS Basics', 'Htmlcss'), ('📊 Data Analysis with Python', 'Data')], max_length=100)),
                ('referral', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
