# Generated by Django 5.2.1 on 2025-06-02 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(6, message='The field must be at least 6 characters long.')]),
        ),
    ]
