# Generated by Django 5.2.1 on 2025-06-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_courses', '0002_auto_add_default_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student', 'course')},
        ),
    ]
