# Generated by Django 5.2.1 on 2025-06-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_courses', '0003_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(through='student_courses.StudentCourse', to='student_courses.course'),
        ),
    ]
