# Generated by Django 5.2.1 on 2025-06-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_courses', '0004_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='student_email_e135f8_idx'),
        ),
    ]
